### ISSUE TITLE
stage I

### ISSUE THREAD

**Issue by rusdevops** [poljkee2010/Explorer1#1]
- [x] 1. Отсутсвует проверка типа ресурса
https://github.com/poljkee2010/Explorer1/blob/c57da50f1ea841fb8b00d238a8312fbbf8d59dee/main.cpp#L19
- [x] 2. Некорректное место записи, смотрите Задание
https://github.com/poljkee2010/Explorer1/blob/c57da50f1ea841fb8b00d238a8312fbbf8d59dee/main.cpp#L25
- [x] 3. Отсутсвует корректности открытия файла лога для записи
https://github.com/poljkee2010/Explorer1/blob/c57da50f1ea841fb8b00d238a8312fbbf8d59dee/main.cpp#L25

**Comment by poljkee2010** [comment]
1) Тип ресурса может быть любой формат текстового файла для записи информации
2) Не понял

**Comment by poljkee2010** [comment]
Что означает проверка типа ресурса? 
2  пункт сделал

**Comment by rusdevops** [comment]
1. Проверка является ли ресурс директорией или файлом
2. ... в файл, путь к файлу задается с помощью переменной окружения `EXPLORER_LOG_PATH`
